import = ["/Users/valerius/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 150, lines = 40 }


[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
