
[env]
TERM = "xterm-256color"

[window]
padding = { x = 2, y = 2 }
dimensions = { columns = 150, lines = 40 }

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
